language: bash
os: linux
dist: xenial
env:
  global:
    - UNIT_TEST=true
    - MODELING_GAUSS=true
    - MODELING_MULTI=true
    - DEPLOY=false
git:
  depth: 1
branches:
  only:
    - master
    - /^develop.*$/
    - test
jobs:
 include:
  - stage: Unit test
    name: Unit test
    if: env(UNIT_TEST)=true
    script: ./TDD/test_travis_docker.sh 'make' 
  - stage: Modeling
    name: Gaussian Reflector
    if: env(MODELING_GAUSS)=true
    script: ./TDD/test_travis_docker.sh 'python -m unittest test_gaussianModelBuild'
  - if: env(MODELING_MULTI)=true
    script: ./TDD/test_travis_docker.sh 'python -m unittest test_multiLayerModelBuild'
    name: Multi Layer
  - stage: Deploy
    name: Deploy
    if: env(DEPLOY)=true
    script: echo "Deploy"
    before_deploy:
      - git config --local user.name "dirack"
      - git config --local user.email "rodolfo_profissional@hotmail.com"
      - export TRAVIS_TAG=$(cat VERSION.md)
      - deploy/build_tag_message.sh
      - git tag -a $TRAVIS_TAG -F tag.deploy
    deploy:
      provider: releases
      token: $GITHUB_TOKEN
      skip_cleanup: true
      draft: true
      script: 'git push --tag'
      on:
        repo: Dirack/creGatherStack
        branch:
          - master
          - test
